package com.xworkz.collections.assignment;

import java.util.ArrayList;
import java.util.Collection;

public class BikeCollection {

	public static void main(String[] args) {
		String bike1 = "Royal Enfield Classic350 Signals Edition";
		String bike2 = "SuzukiGSX-R1000";
		String bike3 = "Suzuki Hayabusa";
		String bike4 = "Yamaha VMAX";
		String bike5 = "Kawasaki Z1000";
		String bike6 = "Kawasaki ZX-12R";
		String bike7 = "Energica Ego";
		String bike8 = "Kawasaki ZX-10R";
		String bike9 = "Kawasaki ZX-14R";
		String bike10 = "Honda CBR1000RR SP";
		String bike11 = "KTM 1290 Super Duke R";
		String bike12 = "EBR 1190RX";
		String bike13 = "Ducati 1199 Panigale";
		String bike14 = "Ducati Monster 1200 S";
		String bike15 = "Kawasaki Ninja H2";
		String bike16 = "Yamaha YZF-R1";
		String bike17 = "Kawasaki ZX-12R";
		String bike18 = "Yamaha FZ1";
		String bike19 = "Suzuki GSXR1000";
		String bike20 = "Ducati 1198S";
		String bike21 = "BMWS1000RR";
		String bike22 = "BMW S1000RR";
		String bike23 = "Yamaha MT-09 (FZ-09)";
		String bike24 = "Ducati 899 Panigale";
		String bike25 = "Triumph Rocket 3";
		String bike26 = "Suzuki Hayabusa";
		String bike27 = "BMW K1300S";
		String bike28 = "Honda CBR954RR";
		String bike29 = "Suzuki GSX-R600";
		String bike30 = "Yamaha YZF-R6";
		String bike31 = "KTM 1190 Adventure";
		String bike32 = "Ducati 959 Panigale";
		String bike33 = "BMW K1300R";
		String bike34 = "BMW K1200R";
		String bike35 = "Suzuki B-King";
		String bike36 = "Suzuki GSX1200W Inazuma";
		String bike37 = "Yamaha YZF-R1";
		String bike38 = "Ducati 1199 Panigale S";
		String bike39 = "Yamaha FZR1000";
		String bike40 = "Suzuki RF900";
		String bike41 = "Honda CBR900RR";
		String bike42 = "Honda CBR1100XX";
		String bike43 = "Ducati 999";
		String bike44 = "Ducati 749S";
		String bike45 = "Kawasaki ZX-6R";
		String bike46 = "Ducati Streetfighter 848";
		String bike47 = "Honda CBR600RR";
		String bike48 = "Suzuki GSX-R750";
		String bike49 = "BMW R1200GS";
		String bike50 = "Yamaha MT-09 (FZ-09)";
		String bike51 = "BMW R nineT";
		String bike52 = "Yamaha YZF-R1";
		String bike53 = "Triumph Street Triple R";
		String bike54 = "Yamaha MT-10/FZ-10";
		String bike55 = "Ducati XDiavel";
		String bike56 = "Yamaha YZF1000R";
		String bike57 = "Ducati Desmosedici RR";
		String bike58 = "Yamaha FJR1300";
		String bike59 = "Kawasaki GPZ900R";
		String bike60 = "Aprilia Tuono RSV-R";

		Collection collection = new ArrayList();

		collection.add(bike1);
		collection.add(bike2);
		collection.add(bike3);
		collection.add(bike4);
		collection.add(bike5);
		collection.add(bike6);
		collection.add(bike7);
		collection.add(bike8);
		collection.add(bike9);
		collection.add(bike10);
		collection.add(bike11);
		collection.add(bike12);
		collection.add(bike13);
		collection.add(bike14);
		collection.add(bike15);
		collection.add(bike16);
		collection.add(bike17);
		collection.add(bike18);
		collection.add(bike19);
		collection.add(bike20);
		collection.add(bike21);
		collection.add(bike22);
		collection.add(bike23);
		collection.add(bike24);
		collection.add(bike25);
		collection.add(bike26);
		collection.add(bike27);
		collection.add(bike28);
		collection.add(bike29);
		collection.add(bike30);
		collection.add(bike30);
		collection.add(bike30);
		collection.add(bike31);
		collection.add(bike32);
		collection.add(bike33);
		collection.add(bike34);
		collection.add(bike35);
		collection.add(bike36);
		collection.add(bike37);
		collection.add(bike38);
		collection.add(bike39);
		collection.add(bike40);
		collection.add(bike41);
		collection.add(bike42);
		collection.add(bike43);
		collection.add(bike44);
		collection.add(bike45);
		collection.add(bike46);
		collection.add(bike47);
		collection.add(bike48);
		collection.add(bike49);
		collection.add(bike50);
		collection.add(bike51);
		collection.add(bike52);
		collection.add(bike53);
		collection.add(bike54);
		collection.add(bike55);
		collection.add(bike56);
		collection.add(bike57);
		collection.add(bike58);
		collection.add(bike59);
		collection.add(bike60);

		System.out.println(collection.size());

	}

}
